export const FIXED_STATION_ORDER = [
  "Laser Etching / Labelling",
  "Screen Printing",
  "SPI (Solder Paste Inspection)",
  "SMT Pick & Place",
  "Hand Placement (SMT)",
  "Reflow",
  "AOI",
  "Visual Inspection",
  "X-Ray",
  "Touch Up",
  "Manual Load (PTH)",
  "Wave Solder",
  "Wash-Clean",
  "Chemical Wash",
  "Hand Solder (No Clean)",
  "Testing",
  "Burn-In",
  "RTV",
  "Conformal Coating",
  "QA Inspection",
  "Depanelisation",
  "Packaging / Shipping",
];